version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./edutrek-server
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://web-database:5432/edutrekadmin
      - SPRING_DATASOURCE_USERNAME=edutrekadmin
      - SPRING_DATASOURCE_PASSWORD=ajsklhdkjashdkujweh233231sadsd1!
    depends_on:
      - web-database

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8000:8080"
    environment:
      ADMINER_DEFAULT_SERVER: web-database
    depends_on:
      - web-database

  web-database:
    container_name: web-database
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ajsklhdkjashdkujweh233231sadsd1!
      - POSTGRES_USER=edutrekadmin
    volumes:
      - ./database/initialisation.sql:/docker-entrypoint-initdb.d/initialisation.sql
      - ./server-data:/var/lib/postgresql/data